-renamesourcefileattribute SourceFile
-keepattributes SourceFile,LineNumberTable # readable stack traces with the mapping file
-keepattributes Signature # generic types (Moshi, Retrofit)
-keepattributes EnclosingMethod
-keepattributes InnerClasses
-keepattributes *Annotation*
