package com.arcao.geocaching4locus.base.util

import android.content.Context
import android.content.res.Resources
import androidx.annotation.PluralsRes
import androidx.annotation.StringRes
import androidx.core.os.ConfigurationCompat
import org.oshkimaadziig.george.androidutils.SpanFormatter
import java.util.Locale

/**
 * Returns formatted text from string resources
 *
 * @param id string resource id
 * @param args arguments for String.format(...)
 * @return formatted SpannedString
 */
@Suppress("NOTHING_TO_INLINE")
inline fun Context.getText(@StringRes id: Int, vararg args: Any) =
    HtmlUtil.applyFix(SpanFormatter.format(getMainLocale(), getText(id), *args))

fun Context.getMainLocale(): Locale {
    val locales = ConfigurationCompat.getLocales(resources.configuration)
    return if (locales.isEmpty) {
        Locale.getDefault()
    } else {
        locales[0]
    }
}

/**
 * Formats the string necessary for grammatically correct pluralization
 * of the given resource ID for the given quantity, using the given arguments.
 * Note that the string is selected based solely on grammatical necessity,
 * and that such rules differ between languages. Do not assume you know which string
 * will be returned for a given quantity. See
 * [String Resources]({@docRoot}guide/topics/resources/string-resource.html#Plurals)
 * for more detail.
 *
 *
 *
 * Substitution of format arguments works as if using [String.format].
 * The resulting string can be text styled.
 *
 * @param id The desired resource identifier, as generated by the aapt
 * tool. This integer encodes the package, type, and resource
 * entry. The value 0 is an invalid identifier.
 * @param quantity The number used to get the correct string for the current language's
 * plural rules.
 * @param formatArgs The format arguments that will be used for substitution.
 * @return CharSequence The string data associated with the resource, plus
 * possibly styled text information.
 * @throws Resources.NotFoundException Throws NotFoundException if the given ID does not exist.
 */
@Suppress("NOTHING_TO_INLINE")
@Throws(Resources.NotFoundException::class)
inline fun Context.getQuantityText(@PluralsRes id: Int, quantity: Int, vararg formatArgs: Any): CharSequence =
    HtmlUtil.applyFix(SpanFormatter.format(getMainLocale(), resources.getQuantityText(id, quantity), *formatArgs))
